name = "Nemo_2512"
author = "PakkHha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7c0bf5842b146c2b530191a58aaace578c99a58b187f3802be64e3037bd7d05"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
