name = "Nemo_2512"
author = "PakkHha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db359e47973b9ac2466ae5ec44b6726a6cf2f3d9cbe49a74013a242415234f56"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
